@startuml
autonumber
title Sequence Diagram: OAuth2 via Google OAuth2

actor Gebruiker
participant "Frontend\n(React.js)" as Frontend
participant "AuthController\n(Spring Boot)" as AuthController
participant "AuthService\n(Spring Boot)" as AuthService
participant "ExternalAPICheck\n(Spring Boot)" as ExternalAPICheck
participant "AuthRepository\n(Spring Boot)" as AuthRepository
participant "Google OAuth2" as Google

Gebruiker -> Frontend: Navigeert naar /login (HTTP)
Frontend -> AuthController: Stuur gebruiker naar loginEndpoint (HTTP)
AuthController -> AuthService: Roep AuthService aan

AuthService -> ExternalAPICheck: Controleert verbinding van externe API
ExternalAPICheck -> Google: Vraagt JWK_SET op (HTTP/JSON)
Google -> ExternalAPICheck: Geeft JWK_SET terug (JSON)
ExternalAPICheck -> AuthService: Verbinding is succesvol (boolean)

AuthService -> Google: Stuurt gebruiker naar Google OAuth2 (HTTP/JSON)
Google -> AuthService: Stuurt OAuth token terug (JSON)
AuthService -> Google: Haal gebruikersinformatie op (HTTP/JSON)
Google -> AuthService: Gebruikersinformatie terug (JSON)

AuthService -> AuthRepository: 12. Sla gebruiker op (JDBC)
AuthService -> AuthController: 13. Genereer JWT token obv email
AuthController -> Frontend: 14. Stuur gebruiker terug met JWT token (HTTP)

@enduml
