@startuml
title User Login Flow

actor Reiziger
participant "TripTop Frontend" as ttfe

participant "PaymentController" as paymentcontroller
participant "PaymentService" as paymentservice
participant "PaymentDAO" as paymentdao
participant "StripeAdapter" as stripeadapter
participant "StripeAPI" as stripeapi

database "H2 Database" as h2


Reiziger -> ttfe : Betaalt voor een activiteit
ttfe -> paymentcontroller : Stuurt HTTP request naar .../payment/process
paymentcontroller -> paymentservice : ResponseEntity<String> response = paymentService.pay(payment)
paymentservice -> stripeadapter : ResponseEntity<String> response = StripeAdapter.processPayment(payment)
stripeadapter -> stripeapi : posts payment to StripeAPI
paymentservice -> paymentdao : paymentDAO.insertPayment(payment)
paymentdao -> h2 : 


@enduml
