@startuml
title Context diagram voor TripTop

skinparam DefaultTextAlignment center

' Define the main system with stereotype
rectangle "<<System>>\n\nTripTop Applicatie\nWil een reis binnen/\nnaar Nederland maken" as TripTop_Applicatie #lightblue

' Define external entities with stereotypes
rectangle "<<Person>>\n\nReiziger\nWil een reis binnen/\n naar Nederland maken" as Reiziger #blue

rectangle "<<External System>>\n\nBetalings Service\nVerzorgt de betalingen voor de\nreizen (Bijv. Stripe, IDEAL, etc.)" as BetalingsSysteem
rectangle "<<External System>>\n\nIdentity Provider API\nBeheert alle Accounts voor TripTop\n(bijv. Google, Microsoft, etc.)" as IdentityProviderAPI
rectangle "<<External System>>\n\nGoogle Maps API\nBiedt kaarten en routebeschrijvingen" as GoogleMaps
rectangle "<<External System>>\n\nVervoerder API\nBiedt informatie over het (openbaar)\nvervoer in Nederland (bijv. NS, Arriva,\nBreng, KLM, etc.)" as VervoerderAPI
rectangle "<<External System>>\n\nActiviteiten API\nBiedt informatie over activiteiten in\nNederland (bijv. TripAdvisor,\nGetYourGuide, etc.)" as ActiviteitenAPI
rectangle "<<External System>>\n\nOvernachtingen API\nBiedt informatie over\novernachtingsmogelijkheden\nin Nederland (bijv. Booking.com,\nAirbnb, eigen beheer etc.)" as OvernachtingenAPI
rectangle "<<External System>>\n\nAuto Verhuur API\nBiedt informatie over autoverhuur\nin Nederland (bijv. Hertz,\nEuropcar, etc.)" as AutoVerhuurAPI

' Relationships
Reiziger --> TripTop_Applicatie : Plant een reis in Nederland
TripTop_Applicatie --> BetalingsSysteem : Verwerkt betalingen
TripTop_Applicatie --> IdentityProviderAPI : Beheert accounts
TripTop_Applicatie --> GoogleMaps : Toont kaarten en routebeschrijvingen
TripTop_Applicatie --> VervoerderAPI : Toont informatie over het vervoer
TripTop_Applicatie --> ActiviteitenAPI : Toont informatie over activiteiten
TripTop_Applicatie --> OvernachtingenAPI : Toont informatie over overnachtingsmogelijkheden
TripTop_Applicatie --> AutoVerhuurAPI : Toont informatie over autoverhuur

@enduml
