@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Dynamic diagram Oauth2 via Google Oauth2

Person(User, "Gebruiker", "De gebruiker van de applicatie")


System_Boundary("key_boundary", "Triptop Applicatie", $tags="") {
System(Frontend, "Frontend", "React.js")
System_Boundary("Backend", "Backend Applicatie", $tags="") {
    Component(AuthController, "AuthController", "Spring Boot", "Controller voor authenticatie")
    Component(AuthService, "AuthService", "Spring Boot", "Service voor authenticatie")
    Component(AuthRepository, "AuthRepository", "Spring Boot", "Repository voor authenticatie")
    Component(ExternalAPICheck, "ExternalAPICheck", "Spring Boot", "Controller voor externe API controle")
}
}
System_Ext(Google, "Google Oauth2", "Google Oauth2")

Rel_D(User, Frontend, "1. Gebruiker navigeert naar /login", $techn="HTTP(S)")
Rel_D(Frontend, Backend, "2. Stuur gebruiker naar de loginEndpoint op de backend", $techn="HTTP(S)")
Rel(Backend, AuthController, "3. Stuur gebruiker naar de login endpoint")
Rel(AuthController, AuthService, "4. Roept de AuthService aan om de gebruiker door te sturen naar Google Oauth2")
Rel_L(AuthService, ExternalAPICheck, "5. De AuthService delegeert de taak van het testen van de verbinding naar de ExternalAPICheck")
Rel_D(ExternalAPICheck, Google, "6. Stuur een verzoek naar de JWK_SET van Google om de verbinding te testen", "HTTP/JSON")
Rel_U(Google, ExternalAPICheck, "7. Google Oauth2 stuurt een JWK_SET terug", "JSON")
Rel_R(ExternalAPICheck, AuthService, "8. Stuurt terug naar de AuthService dat er een goede verbinding is", "boolean")
Rel(AuthService, Google, "9. Stuur gebruiker naar Google Oauth2", "HTTP/JSON")
Rel_U(Google, AuthService, "10. Google Oauth2 stuurt een OAuth token terug", "JSON")
Rel_D(AuthService, Google, "11. Roept Google Oauth2 aan om de gebruikersinformatie op te halen met het Oauth token", "HTTP/JSON")
Rel_U(Google, AuthService, "12. Google Oauth2 stuurt de gebruikersinformatie terug", "JSON")
Rel_R(AuthService, AuthRepository, "13. Slaat de gebruiker op in de database", "JDBC")

@enduml