@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram voor backend van TravelExpensePro

Container(frontend, "TravelExpensePro Frontend", "React, HTML, CSS", "Frontend voor reiskosten invoeren en lezen.")

Container_Boundary(api, "Backend van TravelExpensePro") {
    Component(expensecontroller, "EnterExpenseController", "Spring Boot, Java", "Slaat ingevoerde reiskosten op.")
    Component(logincontroller, "LoginController", "Spring Boot, Java", "Authoriseerd gebruiker o.b.v. inloggegevens.")
    Component(retrievecontroller, "RetrieveAllExpensesController", "Spring Boot, Java", "Haalt alle reiskosten op.")

    Component(expensedao, "ExpenseDAO", "Spring Boot, Java, SQL", "Slaat/haalt reiskosten op.")
    Component(userdao, "UserDAO", "Spring Boot, Java, SQL", "Slaat/haalt gebruikersgegevens op.")

'    Component(expense, "Expense", "Spring Boot, Java", "Reiskosten domein object.")
'    Component(user, "User", "Spring Boot, Java", "Gebruiker domein object.")

'    Component(expenserowmapper, "ExpenseRowMapper", "Spring Boot, Java", "Slaat gegevens op in reiskosten domein object.")
'    Component(userrowmapper, "UserRowMapper", "Spring Boot, Java", "Slaat gegevens op in gebruikers domein object.")
'    Component(hashrowmapper, "HashRowMapper", "Spring Boot, Java", "Returnt salt.")
'    Component(loginresponse, "LoginResponse", "Spring Boot, Java", "Response DTO voor inloggen.")

    Component(authservice, "AuthenticationService", "Spring Boot, Java", "Maakt tokens aan, en controleert of tokens geldig zijn.")
'    Component(encryptor, "JascryptConfig", "Spring Boot, Java", "Encrypt inloggegevens.")

    Rel(frontend, expensecontroller, "Stuurt reiskosten request naar", "JSON/HTTPS")
    Rel(frontend, retrievecontroller, "Stuurt requests naar", "JSON/HTTPS")
    Rel(frontend, logincontroller, "Stuurt inloggegevens naar", "JSON/HTTPS")

    Rel(expensecontroller, authservice, "Checkt authenticatie/autorisatie", "Java")
    Rel(logincontroller, authservice, "Logt gebruiker in en checkt authenticatie/autorisatie", "Java")
    Rel(retrievecontroller, authservice, "Checkt authenticatie/autorisatie", "Java")

    Rel(expensecontroller, expensedao, "Slaat kosten op via", "Java")
'    Rel(expensecontroller, "expenserowmapper", "Mapt kosten met", "Java")

    Rel(retrievecontroller, expensedao, "Haalt kosten op via", "Java")


    Rel(authservice, userdao, "Haalt gebruikersgegevens op via", "Spring Boot, Java")
'    Rel(authservice, userrowmapper, "Mapt gebruikersgegevens met", "Java")
'    Rel(authservice, hashrowmapper, "Mapt hash met", "Java")
'    Rel(authservice, encryptor, "Encrypteert inloggegevens", "Java")

'    Rel(expensecontroller, expense, "Gebruikt", "Java")
'    Rel(expensedao, expense, "Gebruikt", "Java")
'
'    Rel(logincontroller, userdao, "Haalt gebruiker op via", "Java")
'    Rel(logincontroller, user, "Gebruikt", "Java")
}


System_Ext(h2, "H2 Database", "H2, SQL", "Database voor reiskosten en gebruikersgegevens.")
Rel(expensedao, h2, "Slaat/haalt reiskosten op met", "JDBC, SQL")
Rel(userdao, h2, "Slaat/haalt gebruikersgegevens op met", "JDBC, SQL")

SHOW_LEGEND()
@enduml